# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudPlatform', '0002_auto_20170512_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistoolconnect',
            name='DemandTemplateID_FrontID_BackID',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
    ]
