# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudPlatform', '0003_auto_20170512_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandtemplate',
            name='StartMethodNode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demandtemplatenode',
            name='DemandTemplate_DemandTemplateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cloudPlatform.DemandTemplate'),
        ),
    ]
