# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudPlatform', '0006_auto_20170516_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationDrawInfo',
            fields=[
                ('VisualizationDrawID', models.AutoField(primary_key=True, serialize=False)),
                ('VisualizationDrawName', models.CharField(max_length=45)),
                ('VisualizationDrawDescrip', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='visualizationdraw',
            name='VisualizationDrawID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudPlatform.VisualizationDrawInfo'),
        ),
    ]
