# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Math.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Math.proto',
  package='tools',
  syntax='proto3',
  serialized_pb=_b('\n\nMath.proto\x12\x05tools\"#\n\x12SerializedIOStream\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x32\x45\n\x04Math\x12=\n\x03sum\x12\x19.tools.SerializedIOStream\x1a\x19.tools.SerializedIOStream\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SERIALIZEDIOSTREAM = _descriptor.Descriptor(
  name='SerializedIOStream',
  full_name='tools.SerializedIOStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='tools.SerializedIOStream.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['SerializedIOStream'] = _SERIALIZEDIOSTREAM

SerializedIOStream = _reflection.GeneratedProtocolMessageType('SerializedIOStream', (_message.Message,), dict(
  DESCRIPTOR = _SERIALIZEDIOSTREAM,
  __module__ = 'Math_pb2'
  # @@protoc_insertion_point(class_scope:tools.SerializedIOStream)
  ))
_sym_db.RegisterMessage(SerializedIOStream)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class MathStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.sum = channel.unary_unary(
          '/tools.Math/sum',
          request_serializer=SerializedIOStream.SerializeToString,
          response_deserializer=SerializedIOStream.FromString,
          )


  class MathServicer(object):

    def sum(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_MathServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'sum': grpc.unary_unary_rpc_method_handler(
            servicer.sum,
            request_deserializer=SerializedIOStream.FromString,
            response_serializer=SerializedIOStream.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'tools.Math', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaMathServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def sum(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaMathStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def sum(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    sum.future = None


  def beta_create_Math_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('tools.Math', 'sum'): SerializedIOStream.FromString,
    }
    response_serializers = {
      ('tools.Math', 'sum'): SerializedIOStream.SerializeToString,
    }
    method_implementations = {
      ('tools.Math', 'sum'): face_utilities.unary_unary_inline(servicer.sum),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Math_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('tools.Math', 'sum'): SerializedIOStream.SerializeToString,
    }
    response_deserializers = {
      ('tools.Math', 'sum'): SerializedIOStream.FromString,
    }
    cardinalities = {
      'sum': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'tools.Math', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
